services:
  minecraft:
    image: itzg/minecraft-server
    container_name: minecraft
    environment:
      - "EULA=TRUE"
      - "TYPE=PAPER"
      - "MEMORY=7G"
    tty: true
    stdin_open: true
    restart: unless-stopped
    network_mode: host
    volumes:
      # attach a directory relative to the directory containing this compose file
      - ${MINECRAFT_VOLUME_DIR}:/data
